// Mocks generated by Mockito 5.4.4 from annotations
// in masinqo/test/unit_tests/domain/listener_fav_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:masinqo/domain/entities/albums.dart' as _i5;
import 'package:masinqo/infrastructure/listener/listener_favorite/listener_fav_repository.dart'
    as _i6;
import 'package:masinqo/infrastructure/listener/listener_favorite/listener_fav_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeListenerFavService_0 extends _i1.SmartFake
    implements _i2.ListenerFavService {
  _FakeListenerFavService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ListenerFavService].
///
/// See the documentation for Mockito's code generation for more information.
class MockListenerFavService extends _i1.Mock
    implements _i2.ListenerFavService {
  MockListenerFavService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  _i4.Future<List<_i5.Album>> getFavorites(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavorites,
          [token],
        ),
        returnValue: _i4.Future<List<_i5.Album>>.value(<_i5.Album>[]),
      ) as _i4.Future<List<_i5.Album>>);

  @override
  _i4.Future<void> addFavorite(
    String? id,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFavorite,
          [
            id,
            token,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteFavorite(
    String? id,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFavorite,
          [
            id,
            token,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [ListenerFavRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockListenerFavRepository extends _i1.Mock
    implements _i6.ListenerFavRepository {
  MockListenerFavRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ListenerFavService get listenerFavService => (super.noSuchMethod(
        Invocation.getter(#listenerFavService),
        returnValue: _FakeListenerFavService_0(
          this,
          Invocation.getter(#listenerFavService),
        ),
      ) as _i2.ListenerFavService);

  @override
  _i4.Future<List<_i5.Album>> getFavorites(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavorites,
          [token],
        ),
        returnValue: _i4.Future<List<_i5.Album>>.value(<_i5.Album>[]),
      ) as _i4.Future<List<_i5.Album>>);

  @override
  _i4.Future<void> addFavorite(
    String? id,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFavorite,
          [
            id,
            token,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteFavorite(
    String? id,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFavorite,
          [
            id,
            token,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
